app/models.py
import hashlib
from datetime import datetime

from flask import request

from . import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), nullable=False, unique=True, index=True)
    username = db.Column(db.String(64), nullable=False, unique=True, index=True)
    is_admin = db.Column(db.Boolean)
    password_hash = db.Column(db.String(256))
    name = db.Column(db.String(64))
    location = db.Column(db.String(64))
    bio = db.Column(db.Text)
    member_since = db.Column(db.DateTime(), default=datetime.utcnow)
    avatar_hash = db.Column(db.String(256))
    talks = db.relationship('Talk', lazy='dynamic', backref='author')

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if (self.email is not None) and (self.avatar_hash is None):
            self.avatar_hash = hashlib.md5(self.email.encode('utf-8')).hexdigest()

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def gravatar(self, size=100, default='identicon', rating='g'):
        if request.is_secure:
            url = 'https://secure.gravatar.com/avatar'
        else:
            url = 'http://www.gravatar.com/avatar'
        hash = self.avatar_hash or hashlib.md5(self.email.encode('utf-8')).hexdigest()
        return "{url}/{hash}?s={size}&d={default}&r={rating}".format(url=url, hash=hash, size=size, default=default, rating=rating)

class Talk(db.Model):
    __tablename__ = 'talks'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128), nullable=False)
    description = db.Column(db.Text)
    slides = db.Column(db.Text())
    video = db.Column(db.Text())
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    venue = db.Column(db.String(128))
    venue_url = db.Column(db.String(128))
    date = db.Column(db.DateTime())

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/talks/forms.py
from flask_wtf import Form, FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, DateField
from wtforms.validators import Optional, Length, Required, DataRequired, URL


class ProfileForm(FlaskForm):
    name = StringField('Name', validators=[Optional(), Length(1, 64)])
    location = StringField('Location', validators=[Optional(), Length(1, 64)])
    bio = TextAreaField('Bio')
    submit = SubmitField('Submit')

class TalkForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(1, 128)])
    description = TextAreaField('Description')
    slides = StringField('Slides Embed Code (450 pixels wide)')
    video = StringField('Video Embed Code (450 pixels wide)')
    venue = StringField('Venue',
                        validators=[DataRequired(), Length(1, 128)])
    venue_url = StringField('Venue URL',
                            validators=[Optional(), Length(1, 128), URL()])
    date = DateField('Date')
    submit = SubmitField('Submit')

    def from_model(self, talk):
        self.title.data = talk.title
        self.description.data = talk.description
        self.slides.data = talk.slides
        self.video.data = talk.video
        self.venue.data = talk.venue
        self.venue_url.data = talk.venue_url
        self.date.data = talk.date

    def to_model(self, talk):
        talk.title = self.title.data
        talk.description = self.description.data
        talk.slides = self.slides.data
        talk.video = self.video.data
        talk.venue = self.venue.data
        talk.venue_url = self.venue_url.data
        talk.date = self.date.data

app/__init__.py
from flask import Flask
from config import config
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

bootstrap = Bootstrap
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    from .talks import talks as talks_blueprint
    app.register_blueprint(talks_blueprint)

    # Inicializando app Bootstrap
    bootstrap(app)

    # Inicializando Database
    db.init_app(app)

    # Inicializando Autenticacao
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    login_manager.init_app(app)

    return app

app/talks/__init__.py
from flask import Blueprint
talks = Blueprint('talks', __name__)
from . import routes

app/talks/routes.py
from flask import render_template, flash, redirect, url_for
from flask_login import login_required, current_user

from app import db
from app.auth.forms import ProfileForm
from app.talks.forms import TalkForm
from . import talks
from ..models import User, Talk


@talks.route('/')
def index():
    talk_list = Talk.query.order_by(Talk.date.desc()).all()
    return render_template('talks/index.html', talks=talk_list)

@talks.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    talk_list = user.talks.order_by(Talk.date.desc()).all()
    return render_template('talks/user.html', user=user, talks = talk_list)

@talks.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = ProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.bio = form.bio.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash('Your profile has been updated.')
        return redirect(url_for('talks.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.bio.data = current_user.bio
    return render_template('talks/profile.html', form=form)

@talks.route('/new', methods=['GET', 'POST'])
@login_required
def new_talk():
    form = TalkForm()
    if form.validate_on_submit():
        talk = Talk(author=current_user)
        form.to_model(talk)
        db.session.add(talk)
        db.session.commit()
        flash('The talk was added successfully.')
        return redirect(url_for('.index'))
    return render_template('talks/edit_talk.html', form=form)

@talks.route('/talk/<int:id>', methods=['GET', 'POST'])
def talk(id):
    talk = Talk.query.get_or_404(id)
    headers = {}
    if current_user.is_authenticated:
        headers['X-XSS-Protection'] = '0'
    return render_template('talks/talk.html', talk=talk),\
           200, headers

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Talks{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('talks.index') }}">Talks</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('talks.index') }}">Home</a></li>
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('talks.user', username=current_user.username) }}">Profile</a></li>
                <li><a href="{{ url_for('talks.new_talk') }}">New Talk</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if not current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.login') }}">Presenter Login</a></li>
                {% else %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{{ current_user.gravatar(size=18) }}"> {{ current_user.username }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/talks/_talk_header.html
<div class="talk-header">
    {% if talk.user == current_user %}
    <a class="btn btn-primary pull-right" href="{{ url_for('talks.edit_talk', id=talk.id) }}">Edit</a>
    {% elif current_user.is_admin %}
    <a class="btn btn-danger pull-right" href="{{ url_for('talks.edit_talk', id=talk.id) }}">Edit</a>
    {% endif %}
    <h2><a href="{{ url_for('talks.talk', id=talk.id) }}">{{ talk.title }}</a></h2>
    <h3>{{ talk.description }}</h3>
    <p>
        Presented by <a href="{{ url_for('talks.user', username=talk.author.username) }}">{{ talk.author.username }}</a> at
        {% if talk.venue_url %}
            <a href="{{ talk.venue_url }}">{{ talk.venue }}</a>
        {% else %}
            {{ talk.venue }}
        {% endif %}
        on {{ talk.date }}.
    </p>
</div>

app/templates/talks/_talks.html
<ul class="talk-list">
{% for talk in talks %}
    <li class="talk">
    {% include "talks/_talk_header.html" %}
    </li>
{% endfor %}
</ul>

app/templates/talks/edit_talk.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Talk</h1>
</div>
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/talks/index.html
{% extends "base.html" %}
{% block page_content %}
    {% if current_user.is_authenticated %}
        <h1>Hello {{ current_user.username }}!</h1>
    {% endif %}
    {% if not current_user.is_authenticated %}
        <h1>Hello World!</h1>
    {% endif %}
    {% include "talks/_talks.html" %}
{% endblock %}

app/templates/talks/profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Profile</h1>
</div>
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/talks/talk.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    {% include "talks/_talk_header.html" %}
</div>
<div class="talk-body">
    {% if talk.video %}
    <div class="talk-video">
    {{ talk.video | safe }}
    </div>
    {% endif %}
    {% if talk.slides %}
    <div class="talk-slides">
    {{ talk.slides | safe }}
    </div>
    {% endif %}
</div>
{% if comments %}
<h3 id="comments">Comments</h3>
{% include "talks/_comments.html" %}
<ul class="pager">
    {% if pagination.has_prev %}
    <li class="previous"><a href="{{ url_for('talks.talk', id=talk.id, page=pagination.prev_num) }}#comments">&larr; Older</a></li>
    {% else %}
    <li class="previous disabled"><a href="#">&larr; Older</a></li>
    {% endif %}
    {% if pagination.has_next %}
    <li class="next"><a href="{{ url_for('talks.talk', id=talk.id, page=pagination.next_num) }}#comments">Newer &rarr;</a></li>
    {% else %}
    <li class="next disabled"><a href="#">Newer &rarr;</a></li>
    {% endif %}
</ul>
{% endif %}
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="http://cdnjs.cloudflare.com/ajax/libs/autosize.js/1.18.1/jquery.autosize.min.js"></script>
<script>
    $(document).ready(function() {
        $('#flask-pagedown-body').autosize();
    });
</script>
{% endblock %}

app/templates/talks/user.html
{% extends "base.html" %}
{% block page_content %}
    <div class="page-header user-profile">
        <div class="user-avatar"><img src="{{ user.gravatar(128) }}" /></div>
        <h1>{{ user.username }}</h1>
    </div>
    {% include "talks/_talks.html" %}
{% endblock %}